export const REGION_DEFAULT = 'reg_01KNN7RSPMSP2FNKEG83ZQ0HQ6'

export const countries = [
  { code: 'AF', name: 'Afghanistan', regionId: '' },
  { code: 'AL', name: 'Albania', regionId: '' },
  { code: 'DZ', name: 'Algeria', regionId: '' },
  { code: 'AD', name: 'Andorra', regionId: '' },
  { code: 'AO', name: 'Angola', regionId: '' },
  { code: 'AG', name: 'Antigua and Barbuda', regionId: '' },
  { code: 'AR', name: 'Argentina', regionId: '' },
  { code: 'AM', name: 'Armenia', regionId: '' },
  { code: 'AU', name: 'Australia', regionId: '' },
  { code: 'AT', name: 'Austria', regionId: '' },
  { code: 'AZ', name: 'Azerbaijan', regionId: '' },
  { code: 'BS', name: 'Bahamas', regionId: '' },
  { code: 'BH', name: 'Bahrain', regionId: '' },
  { code: 'BD', name: 'Bangladesh', regionId: '' },
  { code: 'BB', name: 'Barbados', regionId: '' },
  { code: 'BY', name: 'Belarus', regionId: '' },
  { code: 'BE', name: 'Belgium', regionId: '' },
  { code: 'BZ', name: 'Belize', regionId: '' },
  { code: 'BJ', name: 'Benin', regionId: '' },
  { code: 'BT', name: 'Bhutan', regionId: '' },
  { code: 'BO', name: 'Bolivia', regionId: '' },
  { code: 'BA', name: 'Bosnia and Herzegovina', regionId: '' },
  { code: 'BW', name: 'Botswana', regionId: '' },
  { code: 'BR', name: 'Brazil', regionId: '' },
  { code: 'BN', name: 'Brunei', regionId: '' },
  { code: 'BG', name: 'Bulgaria', regionId: '' },
  { code: 'BF', name: 'Burkina Faso', regionId: '' },
  { code: 'BI', name: 'Burundi', regionId: '' },
  { code: 'CV', name: 'Cabo Verde', regionId: '' },
  { code: 'KH', name: 'Cambodia', regionId: '' },
  { code: 'CM', name: 'Cameroon', regionId: '' },
  { code: 'CA', name: 'Canada', regionId: '' },
  { code: 'CF', name: 'Central African Republic', regionId: '' },
  { code: 'TD', name: 'Chad', regionId: '' },
  { code: 'CL', name: 'Chile', regionId: '' },
  { code: 'CN', name: 'China', regionId: '' },
  { code: 'CO', name: 'Colombia', regionId: '' },
  { code: 'KM', name: 'Comoros', regionId: '' },
  { code: 'CG', name: 'Congo', regionId: '' },
  { code: 'CD', name: 'Congo (DRC)', regionId: '' },
  { code: 'CR', name: 'Costa Rica', regionId: '' },
  { code: 'CI', name: "Cote d'Ivoire", regionId: '' },
  { code: 'HR', name: 'Croatia', regionId: '' },
  { code: 'CU', name: 'Cuba', regionId: '' },
  { code: 'CY', name: 'Cyprus', regionId: '' },
  { code: 'CZ', name: 'Czech Republic', regionId: '' },
  { code: 'DK', name: 'Denmark', regionId: '' },
  { code: 'DJ', name: 'Djibouti', regionId: '' },
  { code: 'DM', name: 'Dominica', regionId: '' },
  { code: 'DO', name: 'Dominican Republic', regionId: '' },
  { code: 'EC', name: 'Ecuador', regionId: '' },
  { code: 'EG', name: 'Egypt', regionId: '' },
  { code: 'SV', name: 'El Salvador', regionId: '' },
  { code: 'GQ', name: 'Equatorial Guinea', regionId: '' },
  { code: 'ER', name: 'Eritrea', regionId: '' },
  { code: 'EE', name: 'Estonia', regionId: '' },
  { code: 'SZ', name: 'Eswatini', regionId: '' },
  { code: 'ET', name: 'Ethiopia', regionId: '' },
  { code: 'FJ', name: 'Fiji', regionId: '' },
  { code: 'FI', name: 'Finland', regionId: '' },
  { code: 'FR', name: 'France', regionId: '' },
  { code: 'GA', name: 'Gabon', regionId: '' },
  { code: 'GM', name: 'Gambia', regionId: '' },
  { code: 'GE', name: 'Georgia', regionId: '' },
  { code: 'DE', name: 'Germany', regionId: '' },
  { code: 'GH', name: 'Ghana', regionId: '' },
  { code: 'GR', name: 'Greece', regionId: '' },
  { code: 'GD', name: 'Grenada', regionId: '' },
  { code: 'GT', name: 'Guatemala', regionId: '' },
  { code: 'GN', name: 'Guinea', regionId: '' },
  { code: 'GW', name: 'Guinea-Bissau', regionId: '' },
  { code: 'GY', name: 'Guyana', regionId: '' },
  { code: 'HT', name: 'Haiti', regionId: '' },
  { code: 'HN', name: 'Honduras', regionId: '' },
  { code: 'HU', name: 'Hungary', regionId: '' },
  { code: 'IS', name: 'Iceland', regionId: '' },
  { code: 'IN', name: 'India', regionId: '' },
  { code: 'ID', name: 'Indonesia', regionId: '' },
  { code: 'IR', name: 'Iran', regionId: '' },
  { code: 'IQ', name: 'Iraq', regionId: '' },
  { code: 'IE', name: 'Ireland', regionId: '' },
  { code: 'IL', name: 'Israel', regionId: '' },
  { code: 'IT', name: 'Italy', regionId: '' },
  { code: 'JM', name: 'Jamaica', regionId: '' },
  { code: 'JP', name: 'Japan', regionId: '' },
  { code: 'JO', name: 'Jordan', regionId: '' },
  { code: 'KZ', name: 'Kazakhstan', regionId: '' },
  { code: 'KE', name: 'Kenya', regionId: '' },
  { code: 'KI', name: 'Kiribati', regionId: '' },
  { code: 'KP', name: 'North Korea', regionId: '' },
  { code: 'KR', name: 'South Korea', regionId: '' },
  { code: 'KW', name: 'Kuwait', regionId: '' },
  { code: 'KG', name: 'Kyrgyzstan', regionId: '' },
  { code: 'LA', name: 'Laos', regionId: '' },
  { code: 'LV', name: 'Latvia', regionId: '' },
  { code: 'LB', name: 'Lebanon', regionId: '' },
  { code: 'LS', name: 'Lesotho', regionId: '' },
  { code: 'LR', name: 'Liberia', regionId: '' },
  { code: 'LY', name: 'Libya', regionId: '' },
  { code: 'LI', name: 'Liechtenstein', regionId: '' },
  { code: 'LT', name: 'Lithuania', regionId: '' },
  { code: 'LU', name: 'Luxembourg', regionId: '' },
  { code: 'MG', name: 'Madagascar', regionId: '' },
  { code: 'MW', name: 'Malawi', regionId: '' },
  { code: 'MY', name: 'Malaysia', regionId: '' },
  { code: 'MV', name: 'Maldives', regionId: '' },
  { code: 'ML', name: 'Mali', regionId: '' },
  { code: 'MT', name: 'Malta', regionId: '' },
  { code: 'MH', name: 'Marshall Islands', regionId: '' },
  { code: 'MR', name: 'Mauritania', regionId: '' },
  { code: 'MU', name: 'Mauritius', regionId: '' },
  { code: 'MX', name: 'Mexico', regionId: '' },
  { code: 'FM', name: 'Micronesia', regionId: '' },
  { code: 'MD', name: 'Moldova', regionId: '' },
  { code: 'MC', name: 'Monaco', regionId: '' },
  { code: 'MN', name: 'Mongolia', regionId: '' },
  { code: 'ME', name: 'Montenegro', regionId: '' },
  { code: 'MA', name: 'Morocco', regionId: '' },
  { code: 'MZ', name: 'Mozambique', regionId: '' },
  { code: 'MM', name: 'Myanmar', regionId: '' },
  { code: 'NA', name: 'Namibia', regionId: '' },
  { code: 'NR', name: 'Nauru', regionId: '' },
  { code: 'NP', name: 'Nepal', regionId: '' },
  { code: 'NL', name: 'Netherlands', regionId: '' },
  { code: 'NZ', name: 'New Zealand', regionId: '' },
  { code: 'NI', name: 'Nicaragua', regionId: '' },
  { code: 'NE', name: 'Niger', regionId: '' },
  { code: 'NG', name: 'Nigeria', regionId: '' },
  { code: 'MK', name: 'North Macedonia', regionId: '' },
  { code: 'NO', name: 'Norway', regionId: '' },
  { code: 'OM', name: 'Oman', regionId: '' },
  { code: 'PK', name: 'Pakistan', regionId: '' },
  { code: 'PW', name: 'Palau', regionId: '' },
  { code: 'PS', name: 'Palestine', regionId: '' },
  { code: 'PA', name: 'Panama', regionId: '' },
  { code: 'PG', name: 'Papua New Guinea', regionId: '' },
  { code: 'PY', name: 'Paraguay', regionId: '' },
  { code: 'PE', name: 'Peru', regionId: '' },
  { code: 'PH', name: 'Philippines', regionId: 'reg_01KNY0WCJWP61HN944KFBN8XSX' },
  { code: 'PL', name: 'Poland', regionId: '' },
  { code: 'PT', name: 'Portugal', regionId: '' },
  { code: 'PR', name: 'Puerto Rico', regionId: '' },
  { code: 'QA', name: 'Qatar', regionId: '' },
  { code: 'RO', name: 'Romania', regionId: '' },
  { code: 'RU', name: 'Russia', regionId: '' },
  { code: 'RW', name: 'Rwanda', regionId: '' },
  { code: 'KN', name: 'Saint Kitts and Nevis', regionId: '' },
  { code: 'LC', name: 'Saint Lucia', regionId: '' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', regionId: '' },
  { code: 'WS', name: 'Samoa', regionId: '' },
  { code: 'SM', name: 'San Marino', regionId: '' },
  { code: 'ST', name: 'Sao Tome and Principe', regionId: '' },
  { code: 'SA', name: 'Saudi Arabia', regionId: '' },
  { code: 'SN', name: 'Senegal', regionId: '' },
  { code: 'RS', name: 'Serbia', regionId: '' },
  { code: 'SC', name: 'Seychelles', regionId: '' },
  { code: 'SL', name: 'Sierra Leone', regionId: '' },
  { code: 'SG', name: 'Singapore', regionId: '' },
  { code: 'SK', name: 'Slovakia', regionId: '' },
  { code: 'SI', name: 'Slovenia', regionId: '' },
  { code: 'SB', name: 'Solomon Islands', regionId: '' },
  { code: 'SO', name: 'Somalia', regionId: '' },
  { code: 'ZA', name: 'South Africa', regionId: '' },
  { code: 'SS', name: 'South Sudan', regionId: '' },
  { code: 'ES', name: 'Spain', regionId: '' },
  { code: 'LK', name: 'Sri Lanka', regionId: '' },
  { code: 'SD', name: 'Sudan', regionId: '' },
  { code: 'SR', name: 'Suriname', regionId: '' },
  { code: 'SE', name: 'Sweden', regionId: '' },
  { code: 'CH', name: 'Switzerland', regionId: '' },
  { code: 'SY', name: 'Syria', regionId: '' },
  { code: 'TW', name: 'Taiwan', regionId: '' },
  { code: 'TJ', name: 'Tajikistan', regionId: '' },
  { code: 'TZ', name: 'Tanzania', regionId: '' },
  { code: 'TH', name: 'Thailand', regionId: '' },
  { code: 'TL', name: 'Timor-Leste', regionId: '' },
  { code: 'TG', name: 'Togo', regionId: '' },
  { code: 'TO', name: 'Tonga', regionId: '' },
  { code: 'TT', name: 'Trinidad and Tobago', regionId: '' },
  { code: 'TN', name: 'Tunisia', regionId: '' },
  { code: 'TR', name: 'Turkey', regionId: '' },
  { code: 'TM', name: 'Turkmenistan', regionId: '' },
  { code: 'TV', name: 'Tuvalu', regionId: '' },
  { code: 'UG', name: 'Uganda', regionId: '' },
  { code: 'UA', name: 'Ukraine', regionId: '' },
  { code: 'AE', name: 'United Arab Emirates', regionId: '' },
  { code: 'GB', name: 'United Kingdom', regionId: '' },
  { code: 'US', name: 'United States', regionId: '' },
  { code: 'UY', name: 'Uruguay', regionId: '' },
  { code: 'UZ', name: 'Uzbekistan', regionId: '' },
  { code: 'VU', name: 'Vanuatu', regionId: '' },
  { code: 'VA', name: 'Vatican City', regionId: '' },
  { code: 'VE', name: 'Venezuela', regionId: '' },
  { code: 'VN', name: 'Vietnam', regionId: '' },
  { code: 'YE', name: 'Yemen', regionId: '' },
  { code: 'ZM', name: 'Zambia', regionId: '' },
  { code: 'ZW', name: 'Zimbabwe', regionId: '' },
]

export function getRegionId(countryCode: string | null | undefined): string {
  if (!countryCode) return REGION_DEFAULT
  const country = countries.find(c => c.code === countryCode.toUpperCase())
  return country?.regionId || REGION_DEFAULT
}
