/**
 * Pure country data + Medusa region lookups. Imported by `config/regions.ts`
 * at module load time (synchronous) and re-exposed through `basicStore` for
 * component consumers. Do not import anything from `~/config/regions` or
 * `~/stores/*` here — this module must remain free of circular dependencies.
 */

export const DEFAULT_MEDUSA_REGION_ID = 'reg_01KNN7RSPMSP2FNKEG83ZQ0HQ6'

export interface Country {
  code: string
  name: string
  regionId: string
}

export const COUNTRY_LIST: Country[] = [
  { code: 'AF', name: 'Afghanistan', regionId: '' },
  { code: 'AL', name: 'Albania', regionId: '' },
  { code: 'DZ', name: 'Algeria', regionId: '' },
  { code: 'AD', name: 'Andorra', regionId: '' },
  { code: 'AO', name: 'Angola', regionId: '' },
  { code: 'AG', name: 'Antigua and Barbuda', regionId: '' },
  { code: 'AR', name: 'Argentina', regionId: '' },
  { code: 'AM', name: 'Armenia', regionId: '' },
  { code: 'AU', name: 'Australia', regionId: '' },
  { code: 'AT', name: 'Austria', regionId: '' },
  { code: 'AZ', name: 'Azerbaijan', regionId: '' },
  { code: 'BS', name: 'Bahamas', regionId: '' },
  { code: 'BH', name: 'Bahrain', regionId: '' },
  { code: 'BD', name: 'Bangladesh', regionId: '' },
  { code: 'BB', name: 'Barbados', regionId: '' },
  { code: 'BY', name: 'Belarus', regionId: '' },
  { code: 'BE', name: 'Belgium', regionId: '' },
  { code: 'BZ', name: 'Belize', regionId: '' },
  { code: 'BJ', name: 'Benin', regionId: '' },
  { code: 'BT', name: 'Bhutan', regionId: '' },
  { code: 'BO', name: 'Bolivia', regionId: '' },
  { code: 'BA', name: 'Bosnia and Herzegovina', regionId: '' },
  { code: 'BW', name: 'Botswana', regionId: '' },
  { code: 'BR', name: 'Brazil', regionId: '' },
  { code: 'BN', name: 'Brunei', regionId: '' },
  { code: 'BG', name: 'Bulgaria', regionId: '' },
  { code: 'BF', name: 'Burkina Faso', regionId: '' },
  { code: 'BI', name: 'Burundi', regionId: '' },
  { code: 'CV', name: 'Cabo Verde', regionId: '' },
  { code: 'KH', name: 'Cambodia', regionId: '' },
  { code: 'CM', name: 'Cameroon', regionId: '' },
  { code: 'CA', name: 'Canada', regionId: '' },
  { code: 'CF', name: 'Central African Republic', regionId: '' },
  { code: 'TD', name: 'Chad', regionId: '' },
  { code: 'CL', name: 'Chile', regionId: '' },
  { code: 'CN', name: 'China', regionId: '' },
  { code: 'CO', name: 'Colombia', regionId: '' },
  { code: 'KM', name: 'Comoros', regionId: '' },
  { code: 'CG', name: 'Congo', regionId: '' },
  { code: 'CD', name: 'Congo (DRC)', regionId: '' },
  { code: 'CR', name: 'Costa Rica', regionId: '' },
  { code: 'CI', name: "Cote d'Ivoire", regionId: '' },
  { code: 'HR', name: 'Croatia', regionId: '' },
  { code: 'CU', name: 'Cuba', regionId: '' },
  { code: 'CY', name: 'Cyprus', regionId: '' },
  { code: 'CZ', name: 'Czech Republic', regionId: '' },
  { code: 'DK', name: 'Denmark', regionId: '' },
  { code: 'DJ', name: 'Djibouti', regionId: '' },
  { code: 'DM', name: 'Dominica', regionId: '' },
  { code: 'DO', name: 'Dominican Republic', regionId: '' },
  { code: 'EC', name: 'Ecuador', regionId: '' },
  { code: 'EG', name: 'Egypt', regionId: '' },
  { code: 'SV', name: 'El Salvador', regionId: '' },
  { code: 'GQ', name: 'Equatorial Guinea', regionId: '' },
  { code: 'ER', name: 'Eritrea', regionId: '' },
  { code: 'EE', name: 'Estonia', regionId: '' },
  { code: 'SZ', name: 'Eswatini', regionId: '' },
  { code: 'ET', name: 'Ethiopia', regionId: '' },
  { code: 'FJ', name: 'Fiji', regionId: '' },
  { code: 'FI', name: 'Finland', regionId: '' },
  { code: 'FR', name: 'France', regionId: '' },
  { code: 'GA', name: 'Gabon', regionId: '' },
  { code: 'GM', name: 'Gambia', regionId: '' },
  { code: 'GE', name: 'Georgia', regionId: '' },
  { code: 'DE', name: 'Germany', regionId: '' },
  { code: 'GH', name: 'Ghana', regionId: '' },
  { code: 'GR', name: 'Greece', regionId: '' },
  { code: 'GD', name: 'Grenada', regionId: '' },
  { code: 'GT', name: 'Guatemala', regionId: '' },
  { code: 'GN', name: 'Guinea', regionId: '' },
  { code: 'GW', name: 'Guinea-Bissau', regionId: '' },
  { code: 'GY', name: 'Guyana', regionId: '' },
  { code: 'HT', name: 'Haiti', regionId: '' },
  { code: 'HN', name: 'Honduras', regionId: '' },
  { code: 'HU', name: 'Hungary', regionId: '' },
  { code: 'IS', name: 'Iceland', regionId: '' },
  { code: 'IN', name: 'India', regionId: '' },
  { code: 'ID', name: 'Indonesia', regionId: '' },
  { code: 'IR', name: 'Iran', regionId: '' },
  { code: 'IQ', name: 'Iraq', regionId: '' },
  { code: 'IE', name: 'Ireland', regionId: '' },
  { code: 'IL', name: 'Israel', regionId: '' },
  { code: 'IT', name: 'Italy', regionId: '' },
  { code: 'JM', name: 'Jamaica', regionId: '' },
  { code: 'JP', name: 'Japan', regionId: '' },
  { code: 'JO', name: 'Jordan', regionId: '' },
  { code: 'KZ', name: 'Kazakhstan', regionId: '' },
  { code: 'KE', name: 'Kenya', regionId: '' },
  { code: 'KI', name: 'Kiribati', regionId: '' },
  { code: 'KP', name: 'North Korea', regionId: '' },
  { code: 'KR', name: 'South Korea', regionId: '' },
  { code: 'KW', name: 'Kuwait', regionId: '' },
  { code: 'KG', name: 'Kyrgyzstan', regionId: '' },
  { code: 'LA', name: 'Laos', regionId: '' },
  { code: 'LV', name: 'Latvia', regionId: '' },
  { code: 'LB', name: 'Lebanon', regionId: '' },
  { code: 'LS', name: 'Lesotho', regionId: '' },
  { code: 'LR', name: 'Liberia', regionId: '' },
  { code: 'LY', name: 'Libya', regionId: '' },
  { code: 'LI', name: 'Liechtenstein', regionId: '' },
  { code: 'LT', name: 'Lithuania', regionId: '' },
  { code: 'LU', name: 'Luxembourg', regionId: '' },
  { code: 'MG', name: 'Madagascar', regionId: '' },
  { code: 'MW', name: 'Malawi', regionId: '' },
  { code: 'MY', name: 'Malaysia', regionId: '' },
  { code: 'MV', name: 'Maldives', regionId: '' },
  { code: 'ML', name: 'Mali', regionId: '' },
  { code: 'MT', name: 'Malta', regionId: '' },
  { code: 'MH', name: 'Marshall Islands', regionId: '' },
  { code: 'MR', name: 'Mauritania', regionId: '' },
  { code: 'MU', name: 'Mauritius', regionId: '' },
  { code: 'MX', name: 'Mexico', regionId: '' },
  { code: 'FM', name: 'Micronesia', regionId: '' },
  { code: 'MD', name: 'Moldova', regionId: '' },
  { code: 'MC', name: 'Monaco', regionId: '' },
  { code: 'MN', name: 'Mongolia', regionId: '' },
  { code: 'ME', name: 'Montenegro', regionId: '' },
  { code: 'MA', name: 'Morocco', regionId: '' },
  { code: 'MZ', name: 'Mozambique', regionId: '' },
  { code: 'MM', name: 'Myanmar', regionId: '' },
  { code: 'NA', name: 'Namibia', regionId: '' },
  { code: 'NR', name: 'Nauru', regionId: '' },
  { code: 'NP', name: 'Nepal', regionId: '' },
  { code: 'NL', name: 'Netherlands', regionId: '' },
  { code: 'NZ', name: 'New Zealand', regionId: '' },
  { code: 'NI', name: 'Nicaragua', regionId: '' },
  { code: 'NE', name: 'Niger', regionId: '' },
  { code: 'NG', name: 'Nigeria', regionId: '' },
  { code: 'MK', name: 'North Macedonia', regionId: '' },
  { code: 'NO', name: 'Norway', regionId: '' },
  { code: 'OM', name: 'Oman', regionId: '' },
  { code: 'PK', name: 'Pakistan', regionId: '' },
  { code: 'PW', name: 'Palau', regionId: '' },
  { code: 'PS', name: 'Palestine', regionId: '' },
  { code: 'PA', name: 'Panama', regionId: '' },
  { code: 'PG', name: 'Papua New Guinea', regionId: '' },
  { code: 'PY', name: 'Paraguay', regionId: '' },
  { code: 'PE', name: 'Peru', regionId: '' },
  { code: 'PH', name: 'Philippines', regionId: 'reg_01KNY0WCJWP61HN944KFBN8XSX' },
  { code: 'PL', name: 'Poland', regionId: '' },
  { code: 'PT', name: 'Portugal', regionId: '' },
  { code: 'PR', name: 'Puerto Rico', regionId: '' },
  { code: 'QA', name: 'Qatar', regionId: '' },
  { code: 'RO', name: 'Romania', regionId: '' },
  { code: 'RU', name: 'Russia', regionId: '' },
  { code: 'RW', name: 'Rwanda', regionId: '' },
  { code: 'KN', name: 'Saint Kitts and Nevis', regionId: '' },
  { code: 'LC', name: 'Saint Lucia', regionId: '' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', regionId: '' },
  { code: 'WS', name: 'Samoa', regionId: '' },
  { code: 'SM', name: 'San Marino', regionId: '' },
  { code: 'ST', name: 'Sao Tome and Principe', regionId: '' },
  { code: 'SA', name: 'Saudi Arabia', regionId: '' },
  { code: 'SN', name: 'Senegal', regionId: '' },
  { code: 'RS', name: 'Serbia', regionId: '' },
  { code: 'SC', name: 'Seychelles', regionId: '' },
  { code: 'SL', name: 'Sierra Leone', regionId: '' },
  { code: 'SG', name: 'Singapore', regionId: '' },
  { code: 'SK', name: 'Slovakia', regionId: '' },
  { code: 'SI', name: 'Slovenia', regionId: '' },
  { code: 'SB', name: 'Solomon Islands', regionId: '' },
  { code: 'SO', name: 'Somalia', regionId: '' },
  { code: 'ZA', name: 'South Africa', regionId: '' },
  { code: 'SS', name: 'South Sudan', regionId: '' },
  { code: 'ES', name: 'Spain', regionId: '' },
  { code: 'LK', name: 'Sri Lanka', regionId: '' },
  { code: 'SD', name: 'Sudan', regionId: '' },
  { code: 'SR', name: 'Suriname', regionId: '' },
  { code: 'SE', name: 'Sweden', regionId: '' },
  { code: 'CH', name: 'Switzerland', regionId: '' },
  { code: 'SY', name: 'Syria', regionId: '' },
  { code: 'TW', name: 'Taiwan', regionId: '' },
  { code: 'TJ', name: 'Tajikistan', regionId: '' },
  { code: 'TZ', name: 'Tanzania', regionId: '' },
  { code: 'TH', name: 'Thailand', regionId: '' },
  { code: 'TL', name: 'Timor-Leste', regionId: '' },
  { code: 'TG', name: 'Togo', regionId: '' },
  { code: 'TO', name: 'Tonga', regionId: '' },
  { code: 'TT', name: 'Trinidad and Tobago', regionId: '' },
  { code: 'TN', name: 'Tunisia', regionId: '' },
  { code: 'TR', name: 'Turkey', regionId: '' },
  { code: 'TM', name: 'Turkmenistan', regionId: '' },
  { code: 'TV', name: 'Tuvalu', regionId: '' },
  { code: 'UG', name: 'Uganda', regionId: '' },
  { code: 'UA', name: 'Ukraine', regionId: '' },
  { code: 'AE', name: 'United Arab Emirates', regionId: '' },
  { code: 'GB', name: 'United Kingdom', regionId: '' },
  { code: 'US', name: 'United States', regionId: '' },
  { code: 'UY', name: 'Uruguay', regionId: '' },
  { code: 'UZ', name: 'Uzbekistan', regionId: '' },
  { code: 'VU', name: 'Vanuatu', regionId: '' },
  { code: 'VA', name: 'Vatican City', regionId: '' },
  { code: 'VE', name: 'Venezuela', regionId: '' },
  { code: 'VN', name: 'Vietnam', regionId: '' },
  { code: 'YE', name: 'Yemen', regionId: '' },
  { code: 'ZM', name: 'Zambia', regionId: '' },
  { code: 'ZW', name: 'Zimbabwe', regionId: '' },
]

export function findCountry(countryCode: string | null | undefined): Country | null {
  if (!countryCode) return null
  return COUNTRY_LIST.find(c => c.code === countryCode.toUpperCase()) ?? null
}

export function getRegionIdForCountry(countryCode: string | null | undefined): string {
  return findCountry(countryCode)?.regionId || DEFAULT_MEDUSA_REGION_ID
}

export function getCountryNameForCode(countryCode: string | null | undefined): string | null {
  return findCountry(countryCode)?.name ?? null
}

// ─── E.164 country calling codes (no leading "+") ────────────────────
// Keyed by ISO 3166-1 alpha-2 to match COUNTRY_LIST.
export const DIAL_CODES: Record<string, string> = {
  AF: '93', AL: '355', DZ: '213', AS: '1', AD: '376', AO: '244', AI: '1', AG: '1',
  AR: '54', AM: '374', AW: '297', AU: '61', AT: '43', AZ: '994', BS: '1', BH: '973',
  BD: '880', BB: '1', BY: '375', BE: '32', BZ: '501', BJ: '229', BM: '1', BT: '975',
  BO: '591', BA: '387', BW: '267', BR: '55', IO: '246', VG: '1', BN: '673', BG: '359',
  BF: '226', BI: '257', KH: '855', CM: '237', CA: '1', CV: '238', KY: '1', CF: '236',
  TD: '235', CL: '56', CN: '86', CO: '57', KM: '269', CG: '242', CD: '243', CK: '682',
  CR: '506', CI: '225', HR: '385', CU: '53', CW: '599', CY: '357', CZ: '420', DK: '45',
  DJ: '253', DM: '1', DO: '1', EC: '593', EG: '20', SV: '503', GQ: '240', ER: '291',
  EE: '372', SZ: '268', ET: '251', FK: '500', FO: '298', FJ: '679', FI: '358', FR: '33',
  GF: '594', PF: '689', GA: '241', GM: '220', GE: '995', DE: '49', GH: '233', GI: '350',
  GR: '30', GL: '299', GD: '1', GP: '590', GU: '1', GT: '502', GG: '44', GN: '224',
  GW: '245', GY: '592', HT: '509', HN: '504', HK: '852', HU: '36', IS: '354', IN: '91',
  ID: '62', IR: '98', IQ: '964', IE: '353', IM: '44', IL: '972', IT: '39', JM: '1',
  JP: '81', JE: '44', JO: '962', KZ: '7', KE: '254', KI: '686', XK: '383', KW: '965',
  KG: '996', LA: '856', LV: '371', LB: '961', LS: '266', LR: '231', LY: '218', LI: '423',
  LT: '370', LU: '352', MO: '853', MG: '261', MW: '265', MY: '60', MV: '960', ML: '223',
  MT: '356', MH: '692', MQ: '596', MR: '222', MU: '230', YT: '262', MX: '52', FM: '691',
  MD: '373', MC: '377', MN: '976', ME: '382', MS: '1', MA: '212', MZ: '258', MM: '95',
  NA: '264', NR: '674', NP: '977', NL: '31', NC: '687', NZ: '64', NI: '505', NE: '227',
  NG: '234', NU: '683', KP: '850', MK: '389', MP: '1', NO: '47', OM: '968', PK: '92',
  PW: '680', PS: '970', PA: '507', PG: '675', PY: '595', PE: '51', PH: '63', PL: '48',
  PT: '351', PR: '1', QA: '974', RE: '262', RO: '40', RU: '7', RW: '250', BL: '590',
  SH: '290', KN: '1', LC: '1', MF: '590', PM: '508', VC: '1', WS: '685', SM: '378',
  ST: '239', SA: '966', SN: '221', RS: '381', SC: '248', SL: '232', SG: '65', SX: '1',
  SK: '421', SI: '386', SB: '677', SO: '252', ZA: '27', KR: '82', SS: '211', ES: '34',
  LK: '94', SD: '249', SR: '597', SE: '46', CH: '41', SY: '963', TW: '886', TJ: '992',
  TZ: '255', TH: '66', TL: '670', TG: '228', TK: '690', TO: '676', TT: '1', TN: '216',
  TR: '90', TM: '993', TC: '1', TV: '688', UG: '256', UA: '380', AE: '971', GB: '44',
  US: '1', UY: '598', UZ: '998', VU: '678', VA: '39', VE: '58', VN: '84', WF: '681',
  YE: '967', ZM: '260', ZW: '263',
}

export function getDialCodeForCountry(countryCode: string | null | undefined): string {
  if (!countryCode) return ''
  return DIAL_CODES[countryCode.toUpperCase()] || ''
}
