<script setup lang="ts">
useSeoMeta({
  title: 'Navitag - Privacy Policy',
  robots: 'index, follow',
})

if (import.meta.client) {
  const { $fbq } = useNuxtApp()
  onMounted(() => {
    $fbq('ViewContent', {
      content_name: 'privacy_policy',
      content_category: 'legal',
    })
  })
}
</script>

<template>
  <div class="max-w-3xl mx-auto px-5 py-10">
    <h1 class="text-3xl font-bold text-gray-900 border-b-2 border-navitag-blue pb-3 mb-2">Privacy Policy</h1>
    <p class="italic text-gray-500 mb-8">Last Updated: June 3, 2026</p>

    <p class="text-gray-700 leading-relaxed mb-6">
      This Privacy Policy explains how <strong>Navitag Technology Systems OPC</strong> ("Navitag", "we", "us", or "our"), a corporation based in Makati, Metro Manila, Philippines, collects, uses, and shares information when you use the <strong>Navitag Track</strong> mobile application, website, and related services (the "App"). We are the data controller responsible for your personal information. By using the App, you agree to the practices described below.
    </p>

    <h2 class="text-xl font-bold text-gray-800 mt-8 mb-4">1. Information We Collect</h2>

    <p class="text-gray-700 leading-relaxed mb-4">
      <strong>Account &amp; Profile Information.</strong> When you create an account, we collect a limited set of information depending on how you sign up:
    </p>
    <ul class="list-disc pl-5 space-y-2 text-gray-700 mb-4">
      <li><strong>Name</strong> — as provided by your Google or Apple account, or as you enter it.</li>
      <li><strong>Email Address</strong> — used to create and identify your user profile. If you sign in with Apple and choose "Hide My Email", we receive an anonymized Apple private-relay address instead of your real email.</li>
      <li><strong>Phone Number</strong> — only if you choose to add one to your profile.</li>
    </ul>
    <p class="text-gray-700 leading-relaxed mb-6">
      You can create an account using <strong>Google Sign-In</strong>, <strong>Sign in with Apple</strong>, or by registering directly with an <strong>email address and password</strong>.
    </p>

    <p class="text-gray-700 leading-relaxed mb-6">
      <strong>Authentication Data &amp; Account Identifier.</strong> We use Firebase Authentication to securely manage your login sessions and protect your account. Each account is assigned a unique user identifier (a Firebase User ID), which we use to identify you across the App and our backend services, and which is also associated with your usage and analytics data.
    </p>

    <p class="text-gray-700 leading-relaxed mb-6">
      <strong>Device &amp; Push Notification Data.</strong> With your permission, we collect a push notification token (and associated device identifiers) so we can deliver notifications and alerts to your device.
    </p>

    <p class="text-gray-700 leading-relaxed mb-6">
      <strong>Usage &amp; Analytics Data.</strong> We use Firebase Analytics to collect information about how you interact with the App — such as screens viewed, features used, and general usage and diagnostic events — to understand and improve the App. We do <strong>not</strong> collect an advertising identifier (Apple IDFA or Google Advertising ID), and we do <strong>not</strong> use this data to track you across other companies' apps or websites.
    </p>

    <p class="text-gray-700 leading-relaxed mb-6">
      <strong>Location of Your Tracking Devices.</strong> The core purpose of the App is to display the location and status of the GPS tracking devices you own or are authorized to access. That location data is generated by your devices and transmitted to our servers, which the App then displays to you.
    </p>

    <div class="bg-blue-50 border-l-4 border-navitag-blue p-4 rounded-r-lg mb-6">
      <p class="text-gray-700 leading-relaxed">
        <strong>The App does not collect your phone's location.</strong> We do not request or access your mobile device's GPS or location services. All location information shown in the App comes from your tracking devices, not from the phone running the App.
      </p>
    </div>

    <h2 class="text-xl font-bold text-gray-800 mt-8 mb-4">2. How We Use Your Information</h2>
    <p class="text-gray-700 leading-relaxed mb-4">We use the information we collect to:</p>
    <ul class="list-disc pl-5 space-y-2 text-gray-700 mb-6">
      <li>Create and maintain your <strong>Navitag Track</strong> account and identify you within the App.</li>
      <li>Provide the App's core functionality, including displaying your tracking devices and delivering notifications and alerts.</li>
      <li>Understand how the App is used so we can fix problems and improve it.</li>
      <li>Ensure the security of our service and prevent fraudulent activity.</li>
      <li>Communicate with you about app updates, security alerts, and support.</li>
    </ul>

    <h2 class="text-xl font-bold text-gray-800 mt-8 mb-4">3. Data Sharing and Third Parties</h2>
    <p class="text-gray-700 leading-relaxed mb-4">
      We do <strong>not</strong> sell your personal data, and we do <strong>not</strong> share it for cross-app or cross-site advertising or tracking. We only share information with service providers necessary for the App's core functionality:
    </p>
    <ul class="list-disc pl-5 space-y-2 text-gray-700 mb-6">
      <li><strong>Firebase (Google)</strong> — secure authentication, push notification delivery (Firebase Cloud Messaging), analytics, and encrypted data storage.</li>
      <li><strong>Google Sign-In</strong> — to facilitate Single Sign-On when you choose to sign in with Google.</li>
      <li><strong>Sign in with Apple</strong> — to facilitate Single Sign-On when you choose to sign in with Apple.</li>
    </ul>
    <p class="text-gray-700 leading-relaxed mb-6">
      We require that any third party with whom we share your data provide the same or an equal level of protection for your personal information as described in this Privacy Policy, and use it only for the purposes set out above.
    </p>
    <p class="text-gray-700 leading-relaxed mb-6">
      We may also disclose information where required to comply with applicable law, legal process, or a lawful government request.
    </p>

    <h2 class="text-xl font-bold text-gray-800 mt-8 mb-4">4. International Data Transfers</h2>
    <p class="text-gray-700 leading-relaxed mb-6">
      Because our service providers operate globally, your personal information may be processed and stored on servers located outside the Philippines, including in the United States. We take reasonable steps to ensure such transfers are protected by appropriate safeguards consistent with this Policy and applicable data protection laws.
    </p>

    <h2 class="text-xl font-bold text-gray-800 mt-8 mb-4">5. Data Retention and Deletion</h2>
    <p class="text-gray-700 leading-relaxed mb-4">We retain your information for as long as your account is active. To delete your data:</p>
    <ul class="list-disc pl-5 space-y-2 text-gray-700 mb-6">
      <li><strong>In-App:</strong> Navigate to <strong>Account &gt; Delete Account</strong>. This permanently deletes your account and associated personal data.</li>
      <li><strong>Revoke Google access:</strong> Visit your Google Account at <a href="https://myaccount.google.com/permissions" class="text-navitag-blue hover:underline">myaccount.google.com/permissions</a> and remove Navitag Track.</li>
      <li><strong>Revoke Apple access:</strong> On your device, go to <strong>Settings &gt; [your name] &gt; Sign in with Apple</strong>, select Navitag Track, and choose <strong>Stop Using Apple ID</strong>.</li>
      <li><strong>Direct Request:</strong> You may use our <NuxtLink to="/delete-account" class="text-navitag-blue hover:underline">Delete Account page</NuxtLink> or <NuxtLink to="/contact" class="text-navitag-blue hover:underline">contact us</NuxtLink> to request permanent deletion of your data. We will process such requests within 30 days.</li>
    </ul>

    <h2 class="text-xl font-bold text-gray-800 mt-8 mb-4">6. Your Privacy Rights</h2>
    <p class="text-gray-700 leading-relaxed mb-4">
      In accordance with the Philippine Data Privacy Act of 2012 (Republic Act No. 10173) and other applicable laws, you have the right to:
    </p>
    <ul class="list-disc pl-5 space-y-2 text-gray-700 mb-6">
      <li>Access the personal information we hold about you.</li>
      <li>Request correction of inaccurate or incomplete information.</li>
      <li>Request deletion of your personal information.</li>
      <li>Object to or withdraw consent for the processing of your information.</li>
      <li>Lodge a complaint with the National Privacy Commission (NPC) of the Philippines.</li>
    </ul>

    <h2 class="text-xl font-bold text-gray-800 mt-8 mb-4">7. Children's Privacy</h2>
    <p class="text-gray-700 leading-relaxed mb-6">
      Navitag Track is not directed to children under the age of 13, and we do not knowingly collect personal information from children. If you believe a child has provided us with personal information, please <NuxtLink to="/contact" class="text-navitag-blue hover:underline">contact us</NuxtLink> and we will take steps to delete it.
    </p>

    <h2 class="text-xl font-bold text-gray-800 mt-8 mb-4">8. Security</h2>
    <p class="text-gray-700 leading-relaxed mb-6">
      We implement industry-standard security measures, including SSL/TLS encryption, to protect your data during transmission and while stored in our secure Firebase environment.
    </p>

    <h2 class="text-xl font-bold text-gray-800 mt-8 mb-4">9. Changes to This Privacy Policy</h2>
    <p class="text-gray-700 leading-relaxed mb-6">
      We may update this Privacy Policy from time to time. When we do, we will revise the "Last Updated" date at the top of this page. We encourage you to review this Policy periodically. Your continued use of the App after any changes constitutes acceptance of the updated Policy.
    </p>

    <h2 class="text-xl font-bold text-gray-800 mt-8 mb-4">10. Contact Us</h2>
    <p class="text-gray-700 leading-relaxed mb-6">
      If you have any questions about this Privacy Policy or our data practices, please <NuxtLink to="/contact" class="text-navitag-blue hover:underline">contact us</NuxtLink>.
    </p>
  </div>
</template>
